### PR TITLE
Fix Fstat() assertion

### LINKED ISSUE #153: "Trying to access array offset on value of type bool" in isPipe()
Running 4.5.0, I'm consistently getting the following error w/ PHP 7.4.5:

> Notice: Trying to access array offset on value of type bool in .../vendor/slim/psr7/src/Stream.php on line 389

The request seems to work, but I get Notice output in the result, ahead of my JSON body.

```
( ! ) Notice: Trying to access array offset on value of type bool in .../vendor/slim/psr7/src/Stream.php on line 389
--


1 | 0.0072 | 361776 | {main}( ) | .../index.php:0
2 | 0.0714 | 467296 | Slim\App->run( ??? ) | .../index.php:30
3 | 3.7541 | 564504 | Slim\App->handle( ??? ) | .../App.php:199
4 | 3.7542 | 564504 | Slim\MiddlewareDispatcher->handle( ??? ) | .../App.php:215
5 | 3.7542 | 564504 | {anonymous-class:.../vendor/slim/slim/Slim/MiddlewareDispatcher.php:127-142}->handle( ??? ) | .../MiddlewareDispatcher.php:81
6 | 3.7542 | 564504 | Slim\Middleware\ErrorMiddleware->process( ???, ??? ) | .../MiddlewareDispatcher.php:140
7 | 3.7542 | 564504 | {anonymous-class:.../vendor/slim/slim/Slim/MiddlewareDispatcher.php:127-142}->handle( ??? ) | .../ErrorMiddleware.php:107
8 | 3.7542 | 564504 | Slim\Middleware\RoutingMiddleware->process( ???, ??? ) | .../MiddlewareDispatcher.php:140
9 | 3.7573 | 573144 | {anonymous-class:.../vendor/slim/slim/Slim/MiddlewareDispatcher.php:127-142}->handle( ??? ) | .../RoutingMiddleware.php:60
10 | 3.7573 | 573144 | Slim\Middleware\BodyParsingMiddleware->process( ???, ??? ) | .../MiddlewareDispatcher.php:140
11 | 3.7574 | 573144 | Slim\Middleware\BodyParsingMiddleware->parseBody( ??? ) | .../BodyParsingMiddleware.php:62
12 | 3.7574 | 573144 | Slim\Psr7\Stream->__toString( ) | .../BodyParsingMiddleware.php:161
13 | 3.7574 | 573144 | Slim\Psr7\Stream->rewind( ) | .../Stream.php:162
14 | 3.7574 | 573144 | Slim\Psr7\Stream->isSeekable( ) | .../Stream.php:299
15 | 3.7574 | 573144 | Slim\Psr7\Stream->isPipe( ) | .../Stream.php:277

{ ... my JSON response ... }
```

The line of code is:

    $this->isPipe = (fstat($this->stream)['mode'] & self::FSTAT_MODE_S_IFIFO) !== 0;

I'm expecting that this error means `$this->stream` is a boolean, but in the debugger I never see this to be the case. It's reliably an object. The error appears to occur on the second call to isPipe().

Note that this all works when errors are disabled in production. It's just causing trouble in dev.

### PR DESCRIPTION
**Pull request by l0gicgate**
Closes #153 

In relation to PHP bug:
https://bugs.php.net/bug.php?id=78386

### CODE REVIEW

File: src/Stream.php [hunk 1]
```diff
@@ -408,7 +408,7 @@ public function isPipe(): bool
             if ($this->stream) {
                 $stats = fstat($this->stream);
 
-                if ($stats) {
+                if (is_array($stats)) {
```
Comment (t0mmy742) [inline src/Stream.php:411]: `use function is_array;` should be added at the top of this file.

Comment (l0gicgate) [reply src/Stream.php:411]: Great find! Thank you
